delimiter $$

CREATE TABLE `SYSTEM_NOTIFICATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ALL_PAGES` tinyint(1) NOT NULL DEFAULT '0',
  `CHANGED_BY` varchar(255) DEFAULT NULL,
  `CREATE_DATE` date DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `LAST_UPDATE` date DEFAULT NULL,
  `MESSAGE` varchar(1000) NOT NULL,
  `NOTIFICATION_SEVERITY` varchar(255) NOT NULL,
  `NOTIFICATION_TYPE` varchar(255) NOT NULL,
  `START_DATE` datetime NOT NULL,
  `UUID` varchar(255) NOT NULL,
  `VERSION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UUID` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

