ALTER TABLE ORG_STORAGE_CONFIG_STORAGE_CONFIGURATION CONVERT TO CHARACTER SET utf8;

ALTER TABLE GROUP_USER_REQUEST CONVERT TO CHARACTER SET utf8;

ALTER TABLE ORG_STORAGE_CONFIG CONVERT TO CHARACTER SET utf8;

ALTER TABLE USER_ROLE CONVERT TO CHARACTER SET utf8;

ALTER TABLE APPLICATION CONVERT TO CHARACTER SET utf8;

ALTER TABLE APPLICATION_SCREENSHOT CONVERT TO CHARACTER SET utf8;

ALTER TABLE USER CONVERT TO CHARACTER SET utf8;

ALTER TABLE ORG_GROUP CONVERT TO CHARACTER SET utf8;

ALTER TABLE APPLICATION_VERSION CONVERT TO CHARACTER SET utf8;

ALTER TABLE STORAGE_CONFIGURATION CONVERT TO CHARACTER SET utf8;

ALTER TABLE ORG_GROUP_GUEST_APPLICATION_VERSION CONVERT TO CHARACTER SET utf8;

ALTER TABLE CATEGORY CONVERT TO CHARACTER SET utf8;

ALTER TABLE ORG_GROUP_APPLICATION CONVERT TO CHARACTER SET utf8;

ALTER TABLE USER_OPENIDIDENTIFIER CONVERT TO CHARACTER SET utf8;

ALTER TABLE ROLE CONVERT TO CHARACTER SET utf8;

ALTER TABLE APP_FILE CONVERT TO CHARACTER SET utf8;

ALTER TABLE INVITATION CONVERT TO CHARACTER SET utf8;

ALTER TABLE ORGANIZATION CONVERT TO CHARACTER SET utf8;

ALTER TABLE USER_DOMAIN CONVERT TO CHARACTER SET utf8;

ALTER TABLE STORABLE CONVERT TO CHARACTER SET utf8;

ALTER TABLE EVENT_WATCH CONVERT TO CHARACTER SET utf8;

ALTER TABLE EVENT_WATCH_TYPE CONVERT TO CHARACTER SET utf8;