--
-- Table structure for table `KEY_VAULT_ENTRY`
--

DROP TABLE IF EXISTS `KEY_VAULT_ENTRY`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `KEY_VAULT_ENTRY` (
  `APPLICATION_TYPE` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `ID` bigint(20) NOT NULL,
  `PARENT_DOMAIN_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK192DF1E5BEAB696E` (`ID`),
  KEY `FK192DF1E54FABDC1A` (`PARENT_DOMAIN_ID`),
  CONSTRAINT `FK192DF1E54FABDC1A` FOREIGN KEY (`PARENT_DOMAIN_ID`) REFERENCES `DOMAIN` (`ID`),
  CONSTRAINT `FK192DF1E5BEAB696E` FOREIGN KEY (`ID`) REFERENCES `STORABLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `IOS_KEY_VAULT_ENTRY`
--

DROP TABLE IF EXISTS `IOS_KEY_VAULT_ENTRY`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `IOS_KEY_VAULT_ENTRY` (
  `DISTRIBUTION_KEY_PASSWORD` varchar(255) NOT NULL,
  `ID` bigint(20) NOT NULL,
  `DISTRIBUTION_CERT_ID` bigint(20) DEFAULT NULL,
  `DISTRIBUTION_KEY_ID` bigint(20) DEFAULT NULL,
  `DISTRIBUTION_PROFILE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK43FCE99344654265` (`ID`),
  KEY `FK43FCE9933EF2BFB4` (`DISTRIBUTION_PROFILE_ID`),
  KEY `FK43FCE993D666CBE` (`DISTRIBUTION_KEY_ID`),
  KEY `FK43FCE99391EB4E03` (`DISTRIBUTION_CERT_ID`),
  CONSTRAINT `FK43FCE99391EB4E03` FOREIGN KEY (`DISTRIBUTION_CERT_ID`) REFERENCES `APP_FILE` (`ID`),
  CONSTRAINT `FK43FCE9933EF2BFB4` FOREIGN KEY (`DISTRIBUTION_PROFILE_ID`) REFERENCES `APP_FILE` (`ID`),
  CONSTRAINT `FK43FCE99344654265` FOREIGN KEY (`ID`) REFERENCES `KEY_VAULT_ENTRY` (`ID`),
  CONSTRAINT `FK43FCE993D666CBE` FOREIGN KEY (`DISTRIBUTION_KEY_ID`) REFERENCES `APP_FILE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `KEY_VAULT_ENTRY_CHILD_DOMAIN`
--

DROP TABLE IF EXISTS `KEY_VAULT_ENTRY_CHILD_DOMAIN`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `KEY_VAULT_ENTRY_CHILD_DOMAIN` (
  `KEY_VAULT_ENTRY_ID` bigint(20) NOT NULL,
  `DOMAIN_ID` bigint(20) NOT NULL,
  KEY `FK939FE981780B256F` (`DOMAIN_ID`),
  KEY `FK939FE981412FAE9F` (`KEY_VAULT_ENTRY_ID`),
  CONSTRAINT `FK939FE981412FAE9F` FOREIGN KEY (`KEY_VAULT_ENTRY_ID`) REFERENCES `KEY_VAULT_ENTRY` (`ID`),
  CONSTRAINT `FK939FE981780B256F` FOREIGN KEY (`DOMAIN_ID`) REFERENCES `DOMAIN` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `PAYMENT_PLAN_RESTRICTION` ADD `APPLICATION_RESIGNER_ENABLED` tinyint(1) DEFAULT '0';

ALTER TABLE `DOMAIN_CONFIGURATION` ADD `APPLICATION_RESIGNER_ENABLED` tinyint(1) DEFAULT '0';