DELIMITER $$

DROP PROCEDURE IF EXISTS `drop_fk_if_exists` $$
CREATE PROCEDURE `drop_fk_if_exists` (
IN param_table_name VARCHAR(100),
IN param_key_name VARCHAR(100)
)
BEGIN
-- Verify the foreign key exists
IF EXISTS (SELECT NULL FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = param_key_name) THEN
-- Turn the parameters into local variables
set @ParamTable = param_table_name ;
set @ParamKey = param_key_name ;
-- Create the full statement to execute
set @StatementToExecute = concat('ALTER TABLE ',@ParamTable,' DROP FOREIGN KEY ',@ParamKey);
-- Prepare and execute the statement that was built
prepare DynamicStatement from @StatementToExecute ;
execute DynamicStatement ;
-- Cleanup the prepared statement
deallocate prepare DynamicStatement ;
END IF;
END $$

DELIMITER ;

ALTER TABLE `INVITATION` MODIFY `DOMAIN_ID` bigint(20) NOT NULL;
ALTER TABLE `INVITATION` MODIFY `ROLE_ID` bigint(20) NOT NULL;
ALTER TABLE `INVITATION` MODIFY `UUID` varchar(255) NOT NULL;
ALTER TABLE `INVITATION` ADD UNIQUE `UUID` (`UUID`);

CALL drop_fk_if_exists('DOMAIN', 'FK_DOMAIN_DOMAINCONFIGURATION_ID');
ALTER TABLE `DOMAIN` CHANGE `DOMAINCONFIGURATION_ID` `DOMAIN_CONFIGURATION_ID` bigint(20) NOT NULL;
ALTER TABLE `DOMAIN` ADD CONSTRAINT `FK_DOMAIN_DOMAIN_CONFIGURATION_ID` FOREIGN KEY (`DOMAIN_CONFIGURATION_ID`) REFERENCES `DOMAIN_CONFIGURATION` (`ID`);

CALL drop_fk_if_exists('KEY_VAULT_ENTRY_CHILD_DOMAIN', 'FK_KEY_VAULT_ENTRY_CHILD_DOMAIN_KEY_VAULT_ENTRY_ID');

ALTER TABLE `APPLICATION` MODIFY `CATEGORY_ID` bigint(20) NOT NULL;
ALTER TABLE `APPLICATION` MODIFY `GROUP_ID` bigint(20) NOT NULL;
ALTER TABLE `CATEGORY` MODIFY `ORGANIZATION_ID` bigint(20) NOT NULL;
ALTER TABLE `ORG_GROUP` MODIFY `ORGANIZATION_ID` bigint(20) NOT NULL;
ALTER TABLE `USER_DOMAIN` MODIFY `USER_ID` bigint(20) NOT NULL;
ALTER TABLE `USER_DOMAIN` MODIFY `ROLE_ID` bigint(20) NOT NULL;
ALTER TABLE `USER_DOMAIN` MODIFY `DOMAIN_ID` bigint(20) NOT NULL;
ALTER TABLE `APP_FILE` MODIFY `STORABLE_ID` bigint(20) NOT NULL;

CALL drop_fk_if_exists('APPLICATION_VERSION', 'FK_APPLICATION_VERSION_APPLICATION_ID');
ALTER TABLE `APPLICATION_VERSION` ADD CONSTRAINT `FK_APPLICATION_VERSION_APPLICATION_ID` FOREIGN KEY (`APPLICATION_ID`) REFERENCES `APPLICATION` (`ID`);