ALTER TABLE APPLICATION
  ADD COLUMN `GROUP_ID` bigint(20) DEFAULT NULL,
  ADD CONSTRAINT `FK_APPLICATION_GROUP_ID` FOREIGN KEY (`GROUP_ID`) REFERENCES `ORG_GROUP` (`ID`);


UPDATE APPLICATION, ORG_GROUP_APPLICATION
  SET APPLICATION.GROUP_ID = ORG_GROUP_APPLICATION.ORG_GROUP_ID
  where APPLICATION.ID = ORG_GROUP_APPLICATION.APPLICATION_ID;