
--
-- Table structure for table `APPLICATION_VERSION_USER_STATISTIC`
--

DROP TABLE IF EXISTS `APPLICATION_VERSION_USER_STATISTIC`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `APPLICATION_VERSION_USER_STATISTIC` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CHANGED_BY` varchar(255) DEFAULT NULL,
  `CREATE_DATE` date DEFAULT NULL,
  `LAST_UPDATE` date DEFAULT NULL,
  `UUID` varchar(255) NOT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `REMOTE_ADDRESS` varchar(255) DEFAULT NULL,
  `USER_AGENT` varchar(255) DEFAULT NULL,
  `APPLICATION_VERSION_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK97EA9412D3446C4E` (`APPLICATION_VERSION_ID`),
  KEY `FK97EA9412921DFD4F` (`USER_ID`),
  CONSTRAINT `FK97EA9412921DFD4F` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `FK97EA9412D3446C4E` FOREIGN KEY (`APPLICATION_VERSION_ID`) REFERENCES `APPLICATION_VERSION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;