delimiter $$

CREATE TABLE `REGION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CHANGED_BY` varchar(255) DEFAULT NULL,
  `CREATE_DATE` date DEFAULT NULL,
  `LAST_UPDATE` date DEFAULT NULL,
  `UUID` varchar(255) NOT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UUID` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

CREATE TABLE `REGION_EMAIL` (
  `REGION_ID` bigint(20) NOT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  KEY `FK_REGION_EMAIL_REGION_ID` (`REGION_ID`),
  CONSTRAINT `FK_REGION_EMAIL_REGION_ID` FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

CREATE TABLE `REGION_LOCALE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CHANGED_BY` varchar(255) DEFAULT NULL,
  `CREATE_DATE` date DEFAULT NULL,
  `LAST_UPDATE` date DEFAULT NULL,
  `UUID` varchar(255) NOT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `COUNTRY` varchar(255) NOT NULL,
  `LANGUAGE` varchar(255) NOT NULL,
  `VARIANT` varchar(255) DEFAULT NULL,
  `REGION_ID` bigint(20) NOT NULL,
  `REGION_LOCALE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UUID` (`UUID`),
  UNIQUE KEY `REGION_LOCALE_ID` (`REGION_LOCALE_ID`),
  KEY `FK_REGION_LOCALE_REGION_LOCALE_ID` (`REGION_LOCALE_ID`),
  KEY `FK_REGION_LOCALE_REGION_ID` (`REGION_ID`),
  CONSTRAINT `FK_REGION_LOCALE_REGION_ID` FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`ID`),
  CONSTRAINT `FK_REGION_LOCALE_REGION_LOCALE_ID` FOREIGN KEY (`REGION_LOCALE_ID`) REFERENCES `REGION_LOCALE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

CREATE TABLE `DOMAIN_LANGUAGE` (
  `DOMAIN_ID` bigint(20) NOT NULL,
  `LANGUAGE` varchar(255) DEFAULT NULL,
  KEY `FK_DOMAIN_LANGUAGE_DOMAIN_ID` (`DOMAIN_ID`),
  CONSTRAINT `FK_DOMAIN_LANGUAGE_DOMAIN_ID` FOREIGN KEY (`DOMAIN_ID`) REFERENCES `DOMAIN` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

CREATE TABLE `DOMAIN_REGION` (
  `DOMAIN_ID` bigint(20) NOT NULL,
  `REGION_ID` bigint(20) NOT NULL,
  UNIQUE KEY `REGION_ID` (`REGION_ID`),
  KEY `FK_DOMAIN_REGION_DOMAIN_ID` (`DOMAIN_ID`),
  KEY `FK_DOMAIN_REGION_REGION_ID` (`REGION_ID`),
  CONSTRAINT `FK_DOMAIN_REGION_REGION_ID` FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`ID`),
  CONSTRAINT `FK_DOMAIN_REGION_DOMAIN_ID` FOREIGN KEY (`DOMAIN_ID`) REFERENCES `DOMAIN` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

CREATE TABLE `REGION_REGION_LOCALE` (
  `REGION_ID` bigint(20) NOT NULL,
  `REGION_LOCALE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`REGION_ID`,`REGION_LOCALE_ID`),
  UNIQUE KEY `REGION_LOCALE_ID` (`REGION_LOCALE_ID`),
  KEY `FK_REGION_REGION_LOCALE_REGION_LOCALE_ID` (`REGION_LOCALE_ID`),
  KEY `FK_REGION_REGION_LOCALE_REGION_ID` (`REGION_ID`),
  CONSTRAINT `FK_REGION_REGION_LOCALE_REGION_ID` FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`ID`),
  CONSTRAINT `FK_REGION_REGION_LOCALE_REGION_LOCALE_ID` FOREIGN KEY (`REGION_LOCALE_ID`) REFERENCES `REGION_LOCALE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


