delimiter $$

CREATE TABLE `CUSTOM_BRANDING` (
  `ID` bigint(20) NOT NULL,
  `LOGO_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CUSTOM_BRANDING_APP_FILE_LOGO_ID` (`LOGO_ID`),
  KEY `FK_CUSTOM_BRANDING_STORABLE_ID` (`ID`),
  CONSTRAINT `FK_CUSTOM_BRANDING_APP_FILE_LOGO_ID` FOREIGN KEY (`LOGO_ID`) REFERENCES `APP_FILE` (`ID`),
  CONSTRAINT `FK_CUSTOM_BRANDING_STORABLE_ID` FOREIGN KEY (`ID`) REFERENCES `STORABLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

delimiter ;

ALTER TABLE `ORGANIZATION` ADD COLUMN `CUSTOM_BRANDING_ID` bigint(20) DEFAULT NULL;
ALTER TABLE `ORGANIZATION` ADD FOREIGN KEY (`CUSTOM_BRANDING_ID`) REFERENCES `CUSTOM_BRANDING` (`ID`);
ALTER TABLE `PAYMENT_PLAN_RESTRICTION` ADD COLUMN `CUSTOM_BRANDING_ENABLED` tinyint(1) DEFAULT NULL;
ALTER TABLE `DOMAIN_CONFIGURATION` ADD COLUMN `CUSTOM_BRANDING_ENABLED` tinyint(1) DEFAULT NULL;