package com.sparc.knappsack.enums;

public enum EventType {
    APPLICATION_VERSION_GROUP_PUBLISH,
    APPLICATION_VERSION_BECOMES_AVAILABLE,
    APPLICATION_VERSION_ORGANIZATION_PUBLISH_REQUEST,
    APPLICATION_VERSION_ORGANIZATION_PUBLISH,
    APPLICATION_VERSION_STATE_CHANGED,
    USER_INVITE,
    USER_ACCOUNT_ACTIVATION,
    USER_PASSWORD_RESET,
    GROUP_ACCESS_REQUEST,
    GROUP_ACCESS_REQUEST_CONFIRMATION
}
