package com.sparc.knappsack.enums;

public enum EventType {
    APPLICATION_VERSION_GROUP_PUBLISH,
    APPLICATION_VERSION_BECOMES_AVAILABLE,
    APPLICATION_VERSION_ORGANIZATION_PUBLISH_REQUEST,
    APPLICATION_VERSION_ORGANIZATION_PUBLISH,
    APPLICATION_VERSION_STATE_CHANGED,
    APPLICATION_VERSION_RESIGN,
    APPLICATION_VERSION_RESIGN_COMPLETE,
    APPLICATION_VERSION_ERROR,
    USER_INVITE,
    USER_ACCOUNT_ACTIVATION,
    USER_ACCOUNT_ACTIVATION_SUCCESS,
    USER_PASSWORD_RESET,
    DOMAIN_ACCESS_REQUEST,
    DOMAIN_USER_ACCESS_REQUEST,
    DOMAIN_USER_ACCESS_REQUEST_CONFIRMATION,
    ORGANIZATION_REGISTRATION,
    BANDWIDTH_LIMIT_REACHED,
}
