
--
-- Table structure for table `EVENT_WATCH`
--

DROP TABLE IF EXISTS `EVENT_WATCH`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `EVENT_WATCH` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CHANGED_BY` varchar(255) DEFAULT NULL,
  `CREATE_DATE` date DEFAULT NULL,
  `LAST_UPDATE` date DEFAULT NULL,
  `NOTIFIABLE_ID` bigint(20) DEFAULT NULL,
  `NOTIFIABLE_TYPE` varchar(255) DEFAULT NULL,
  `UUID` varchar(255) NOT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UUID` (`UUID`),
  UNIQUE KEY `UNQ_EVENT_WATCH_0` (`NOTIFIABLE_TYPE`,`USER_ID`,`NOTIFIABLE_ID`),
  KEY `FK_EVENT_WATCH_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_EVENT_WATCH_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `EVENT_WATCH`
--

LOCK TABLES `EVENT_WATCH` WRITE;
/*!40000 ALTER TABLE `EVENT_WATCH` DISABLE KEYS */;
/*!40000 ALTER TABLE `EVENT_WATCH` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `EVENT_WATCH_TYPE`
--

DROP TABLE IF EXISTS `EVENT_WATCH_TYPE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `EVENT_WATCH_TYPE` (
  `EVENT_WATCH_ID` bigint(20) DEFAULT NULL,
  `EVENT_TYPE_ID` varchar(255) DEFAULT NULL,
  KEY `FK_EVENT_WATCH_TYPE_EVENT_WATCH_ID` (`EVENT_WATCH_ID`),
  CONSTRAINT `FK_EVENT_WATCH_TYPE_EVENT_WATCH_ID` FOREIGN KEY (`EVENT_WATCH_ID`) REFERENCES `EVENT_WATCH` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `EVENT_WATCH_TYPE`
--

LOCK TABLES `EVENT_WATCH_TYPE` WRITE;
/*!40000 ALTER TABLE `EVENT_WATCH_TYPE` DISABLE KEYS */;
/*!40000 ALTER TABLE `EVENT_WATCH_TYPE` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2012-06-12  9:58:37