ALTER TABLE APP_FILE ADD UUID VARCHAR(255);
UPDATE APP_FILE SET UUID=UUID();

ALTER TABLE ORG_GROUP ADD UUID VARCHAR(255);
UPDATE ORG_GROUP SET UUID=UUID();

ALTER TABLE GROUP_USER_REQUEST ADD UUID VARCHAR(255);
UPDATE GROUP_USER_REQUEST SET UUID=UUID();

ALTER TABLE INVITATION ADD UUID VARCHAR(255);
UPDATE INVITATION SET UUID=UUID();

ALTER TABLE STORAGE_CONFIGURATION ADD UUID VARCHAR(255);
UPDATE STORAGE_CONFIGURATION SET UUID=UUID();

ALTER TABLE ORGANIZATION ADD UUID VARCHAR(255);
UPDATE ORGANIZATION SET UUID=UUID();

ALTER TABLE ORG_STORAGE_CONFIG ADD UUID VARCHAR(255);
UPDATE ORG_STORAGE_CONFIG SET UUID=UUID();

ALTER TABLE ROLE ADD UUID VARCHAR(255);
UPDATE ROLE SET UUID=UUID();

ALTER TABLE USER ADD UUID VARCHAR(255);
UPDATE USER SET UUID=UUID();

ALTER TABLE USER_DOMAIN ADD UUID VARCHAR(255);
UPDATE USER_DOMAIN SET UUID=UUID();